### ISSUE TITLE
parent update

### ISSUE THREAD

**Issue by amandaw33** [autopkg/novaksam-recipes#1]
Hi there,

I use your Jss recipe and noticed today I was getting EOF error.

I tracked it down to change in parent.

I hope I'm reporting this in the right place... I'm new to autopkgr and github in general.

Thanks!

<key>ParentRecipe</key>
    <string>com.github.jleggat.AdobeShockwavePlayer.download</string> (not working)

    <key>ParentRecipe</key>
    <string>com.github.jleggat.download.AdobeShockwavePlayer</string> (working)

**Comment by novaksam** [comment]
Yeah I noticed that too; I'll take a look at it today.

**Comment by novaksam** [comment]
I believe he changed the identifier of the parent recipe, so I just copied the download recipe into my repo and modified the pkg recipe accordingly. Once you refresh it should be all good to go!

**Comment by amandaw33** [comment]
will do, thanks!
