### ISSUE TITLE
Recent issue with `AdobeAcrobatReaderDcUpdateInfoProvider'

### ISSUE THREAD

**Issue by shawnhonsberger** [autopkg/novaksam-recipes#13]
I have been working with a recipe for a while from that recently reported an issue. This worked until today, and the repo is updated. AdobeAcrobatDCUpdates.download.recipe works, AdobeAcrobatReaderDCUpdates.pkg.recipe fails with:

`The following recipes failed:
    /path/to/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes/Recipes - pkg/AdobeAcrobatReaderDCUpdates.pkg.recipe
        Unknown processor 'AdobeAcrobatReaderDcUpdateInfoProvider'.`

`update-trust-info` and `run` now fail as well on the jss override of Adobe Acrobat Reader DC Updates.jss.recipe. Is there a change I missed?

**Comment by novaksam** [comment]
I haven't gotten around to making the 'trust' changes they implemented a while back. I'll work on those soon.

And I'll see if I can re-create the Adobe issue.

**Comment by novaksam** [comment]
Interesting that the download recipe works but not the pkg, because this processor is called in the download recipe!

Perhaps try deleting 

> /path/to/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes/Recipes - Download/AdobeAcrobatReaderDcUpdateInfoProvider.pyc

**Comment by shawnhonsberger** [comment]
Hi @novaksam - thank you. I'll try that today.

**Comment by shawnhonsberger** [comment]
Hi @novaksam now the .pkg recipe works with that removed. Thank you. However, I still cannot `update-trust-info` on the .jss override. I get the following:

`Python[55646:18858097] Property list invalid for format: 100 (property lists cannot contain objects of type 'CFNull')
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2435, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2429, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1646, in update_trust_info
    FoundationPlist.writePlist(recipe, recipe_path)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 131, in writePlist
    plistData = _plistToData(plistObject)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 106, in _plistToData
    raise NSPropertyListSerializationException(error)
FoundationPlist.FoundationPlist.NSPropertyListSerializationException: Property list invalid for format.`

**Comment by shawnhonsberger** [comment]
@novaksam do you know what the above issue could be caused by?

**Comment by novaksam** [comment]
@shawnhonsberger Sorry for the delay. I'm not sure what might be causing that.

I suppose what I would do is make a backup of my override, delete it and create a new one so it populates the hashes during the override creation. Then add back any changes you made in your original override.

**Comment by shawnhonsberger** [comment]
Hi @novaksam no worries. I have actually tried that but got the same error. I may have another issue going on. Thank you.
