### ISSUE TITLE
OracleJava8JDK.pkg.recipe:  package is downloaded on every 'run'

### ISSUE THREAD

**Issue by MLBZ521** [autopkg/novaksam-recipes#14]
In the recipe 'OracleJava8JDK.pkg.recipe' deleting the original downloaded file seems to cause AutoPkg to download the package every time, even if it's unchanged.

I believe this commit caused this behavior:  d29e6f9fefbc6ef08a32da1d9c6d7287da4cfc8f

Testing with this line removed, AutoPkg properly recognizes that the source URL item is unchanged.

Two different runs:
>URLDownloader: Storing new Last-Modified header: Wed, 15 Mar 2017 19:26:28 GMT
URLDownloader: Storing new ETag header: "9953fc6bee9effd7bfa5f5199ac99e33:1489611585"

>URLDownloader: Storing new Last-Modified header: Wed, 15 Mar 2017 19:26:28 GMT
URLDownloader: Storing new ETag header: "9953fc6bee9effd7bfa5f5199ac99e33:1489611585"

And the desired result with the line removed:
>URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /path/to/AutoPkg/Cache/com.github.novaksam.pkg.OracleJava8JDK/downloads/Oracle Java 8 JDK.dmg

**Comment by novaksam** [comment]
I can remove that line, I just wish I knew when a new JDK was coming out so I could see if the ETag is coming back differently; I think I had an issue with JDK 8U101 where a new release had come out, but autopkg wasn't deleting the old file.

**Comment by novaksam** [comment]
https://github.com/autopkg/novaksam-recipes/commit/7d335cf161ebf1057679008a9991a8e2993348ce

**Comment by MLBZ521** [comment]
Java expires, I thought it used to be every quarter or six months, but the dates don't add up to that, see:  https://www.java.com/en/download/faq/release_changes.xml

`The expiration date for 8u131 is July 18, 2017. Java expires whenever a new release with security vulnerability fixes becomes available. For systems unable to reach the Oracle Servers, a secondary mechanism expires this JRE (version 8u131) on August 18, 2017. After either condition is met (new release becoming available or expiration date reached), Java will provide additional warnings and reminders to users to update to the newer version.`

So you can expect to see a new version in the next couple months.  Or whenever someone finds another huge security bug.  👍 

Thanks for the fix!
