### ISSUE TITLE
OracleJava8JDK.pkg.recipe - Mismatch in authority names

### ISSUE THREAD

**Issue by MLBZ521** [autopkg/novaksam-recipes#15]
OracleJava8JDK.pkg.recipe is producing "Mismatch in authority names".  The CodeSignatureVerifier processor has been updated in the parent recipe for this child recipe, but since it's checked again, it still failing.

As mentioned #14, regarding the ETag, it is downloading fine and being recognized as a 'new' version with the previous 131 Update present.

**Comment by novaksam** [comment]
https://github.com/autopkg/novaksam-recipes/commit/02f59d983f2c3c2aefcdfecc4cb828f7529bcadc

:)

I fixed mine, though hansen-m's recipe needs to get updated. I'll open a PR with him.

**Comment by novaksam** [comment]
PS, nevermind, it looks like he updates 4 days ago

**Comment by MLBZ521** [comment]
Yep; thanks!
