### ISSUE TITLE
Wacom Intuos Driver getting mismatch in authority names

### ISSUE THREAD

**Issue by multiday** [autopkg/novaksam-recipes#17]
Looks like they changed the authority name for the Wacom Intuos Driver download. Line 49 in Wacomintuos.download.recipe looks like it now should be:

<string>Developer ID Installer: Wacom Technology Corp. (EG27766DY7)</string>

in place of the current:
<string>Developer ID Installer: Wacom Technology Corp.</string>

**Comment by novaksam** [comment]
https://github.com/autopkg/novaksam-recipes/commit/a9faec63e8fc9d93e10a1962815abeb79cf53a8d

Fixed and closing
