### ISSUE TITLE
Certificate authority for Wacom Bamboo hasn't changed (yet?)

### ISSUE THREAD

**Issue by multiday** [autopkg/novaksam-recipes#18]
Wacom changed the authority name for the Wacom Intuos Driver download. And understandable the recipe for the Bamboo driver was updated as well. However, the certificate authority for the Bamboo driver has not changed (yet?). I'm guessing it will when/if they release a new version of the driver. So, not sure that it is worth changing it back at this point. But wanted to make a note of it for anyone that might be wondering.

**Comment by novaksam** [comment]
Should be fixed by https://github.com/autopkg/novaksam-recipes/pull/22
