### ISSUE TITLE
Can't override OS_Requirement in Microsoft AutoUpdated.jss

### ISSUE THREAD

**Issue by everetteallen** [autopkg/novaksam-recipes#21]
What ever I do in an override I can't get <key>OS_REQUIREMENTS</key> to override.  Right now we get this set to 10.10.x every time.  Would be great if we could get this to override or if the value would be set to 10.13.x, 10.12.x, 10.11.x, 10.10.x   (not sure if 10.x will work but might be good if it does).

**Comment by novaksam** [comment]
It's not hardcoded so much as it is automatically generated

```
<dict>
	<key>Arguments</key>
	<dict>
		<key>input_plist_path</key>
		<string>%RECIPE_CACHE_DIR%/downloads/PAYLOAD/Microsoft AutoUpdate.app/Contents/Info.plist</string>
		<key>minimum_os_version</key>
		<string>10.7</string>
	</dict>
	<key>Comment</key>
	<string>Specifying a minimum os version here because the processor 
	that downloads MAU returns it's own variable of the same name 
	and causes issues in the generation of the OS_REQUIREMENTS list</string>
	<key>Processor</key>
	<string>com.github.autopkg.novaksam-recipes.Processors/MinimumOSExtractor</string>
</dict>
```

I wrote a processor a while ago that generates the OS_REQUIREMENTS list based on the information in the info.plist files.

I suppose I could work on making that override-able.

But you may also want to look at the smart group template you're using, because when I did this I switched over to using a template that only needs the minimum OS

```
<criterion>
	<name>Operating System Version</name>
	<priority>3</priority>
	<and_or>and</and_or>
	<search_type>greater than or equal</search_type>
	<value>%OS_MINIMUM%</value>
</criterion>
```

**Comment by portalpie** [comment]
Hello. I am having a similar problem but getting "10.10.x,10.11.x,10.12.x,10.13.x" every time. With the release of 10.14 I am getting failed installs. I too was trying to override when I found this post. Not sure what you are saying about the group template? Thanks

**Comment by portalpie** [comment]
Thank you. Upgrading my AutoPkg box fixed it.
