### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nvts31** [autopkg/novaksam-recipes#24]
Hello,

We receiving below error from the Microsoft AutoUpdate.jss.recipe, but the upload is working correctly. Tried creating new override and flushing recipe cache. Also updated our local override to ignore the downloads folder and we still receive this error on every scheduled run.

Any info would help.

```
local.jss.Microsoft   AutoUpdate QS | Error   in local.jss.Microsoft AutoUpdate QS: Processor:   io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer: Error: [Errno   2] No such file or directory:
/Users/username/Library/AutoPkg/Cache/local.jss.Microsoft AutoUpdate   QS/downloads/Microsoft AutoUpdate-3.15.18011602.pkg
```

Thanks!

**Comment by novaksam** [comment]
```io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer```
I don't believe I'm using this processor... I make a habit of removing pkg's from the downloads folder because I've encountered issues where the ETag on the download doesn't change, so new versions are never downloaded.

**Comment by novaksam** [comment]
I suspect this is already taken care of, closing.
