### ISSUE TITLE
AdobeAcrobatDcUpdateInfoProvider.py generates curl error on download

### ISSUE THREAD

**Issue by amandaw33** [autopkg/novaksam-recipes#26]
Seems like there's a mismatch in the folder structure on reader vs acrobat (1801120035 vs 1801120036) & processor is built on those being same I think

Latest reader version
http://download.adobe.com/pub/adobe/reader/mac/AcrobatDC/1801120036/AcroRdrDC_1801120035_MUI.dmg

Latest acrobat version
http://download.adobe.com/pub/adobe/acrobat/mac/AcrobatDC/1801120035/AcrobatDCUpd1801120035.dmg

**Comment by crystalllized** [comment]
+1 for this issue, it **feels like** changing `MAJOR_VERSION_MATCH_STR` to reflect Acrobat instead of Reader is the fix here but I also don't feel confident enough in my understanding of the processor to put in a pull.

**Comment by amandaw33** [comment]
@crystalllized  looks like someone else did a pull for it here if you didn't see

https://github.com/autopkg/novaksam-recipes/pull/25

**Comment by novaksam** [comment]
Should be resolved by #25
