### ISSUE TITLE
AdobeAcrobatDcUpdateInfoProvider.py is not getting the current version

### ISSUE THREAD

**Issue by LcTrKiD** [autopkg/novaksam-recipes#44]
https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/acrobat/current_version.txt output is not correct so AdobeAcrobatDcUpdateInfoProvider.py is not providing the correct version.

**Comment by novaksam** [comment]
Believe this is fixed with https://github.com/autopkg/novaksam-recipes/commit/df1b32d96e6dd08930580a1b20449d78e614468e
