### ISSUE TITLE
Jamf Pro JSS Issue

### ISSUE THREAD

**Issue by beatlemike** [autopkg/novaksam-recipes#52]
In the JamfPro JSS recipe, I am now getting the following

`Error in local.jss.Jamf Pro: Processor: com.scriptingosx.processors/PathListCopier: Error: module 'FoundationPlist' has no attribute 'FoundationPlistException'`

**Comment by ladygreyjedi** [comment]
Any luck with this issue?

**Comment by novaksam** [comment]
Yeah, sorry, my Mac work hasn't been priority lately with the other stuff I've been doing to prep for remote work. I'll look at it.

**Comment by novaksam** [comment]
https://github.com/autopkg/scriptingosx-recipes/pull/52

**Comment by ladygreyjedi** [comment]
@novaksam Looks like the change you made fixed the issue. Thank you

**Comment by beatlemike** [comment]
Thanks @novaksam! Works great.
