### ISSUE TITLE
AdobeAcrobatReaderDCUpdates Downloader Error

### ISSUE THREAD

**Issue by adem-kfs** [autopkg/novaksam-recipes#64]
`Error in local.pkg.AdobeAcrobatReaderDCUpdates: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://download.adobe.com/pub/adobe/reader/mac/AcrobatDC/2001320074/AcroRdrDCUpd2001320074_MUI.dmg', '--fail', '--output', '/Users/[usernameredacted]/Library/AutoPkg/Cache/local.pkg.AdobeAcrobatReaderDCUpdates/downloads/tmpkhapmlio', '--header', 'If-None-Match: "ac7b0d2-5b2ba1a0e7387"', '--header', 'If-Modified-Since: Wed, 28 Oct 2020 12:14:14 GMT']' returned non-zero exit status 22`

The URL seems to have changed.
Also applies to AdobeAcrobatDCUpdate

**Comment by adem-kfs** [comment]
Disregard, this appears to be Adobe updating the version but not uploading the DMG

**Comment by dev-yeet** [comment]
That's because this is a "delta" update vs full installers for"planned updates. 
This will continue to be an issue until a new planned version comes out so i'd consider this still an issue imo
