### ISSUE TITLE
Removed Audacity.download due to TOS violation

### ISSUE THREAD

**Issue by timsutton** [autopkg/novaksam-recipes#7]
Audacity's download from fosshub is now clearly in violation of their TOS, so I've removed my Audacity.download recipe and made the Audacity.munki recipe I maintain require the `--pkg` argument so that a user may supply their own download. This just involved changing `%pathname%` to `%PKG%` and adding a `PackageRequired` argument so that it's clearer to users how the recipe must be used.

Since you've also got Audacity recipes that ultimately derive from Audacity.download (or are a copy of it), I'm opening this issue on this and a couple other repos.

More details:

https://www.fosshub.com/tos.html

https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub
http://forum.audacityteam.org/viewtopic.php?f=50&t=94040
https://www.reddit.com/r/sysadmin/comments/5g5npg/fosshub_message_for_chocolatey_please_stop_with/

Keeping the fosshub scraping working for this recipe has been a chore and Audacity is rarely ever updated, so I can't say I don't prefer this approach anyway.

Since there also seems to be duplication across a few of @homebysix, @scriptingosx and @novaksam's recipes it might also be a good time to evaluate whether any recipes could be removed in favour of one or another.

**Comment by novaksam** [comment]
FossHUB addressed by https://github.com/autopkg/novaksam-recipes/commit/027873e0e54e16e3a466050d48d1e9ffe3790ca2 

@timsutton were you meaning reevaluate what recipes we use to reduce duplication/reuse across repos?

**Comment by homebysix** [comment]
@novaksam Some de-duplication would be nice. For example, your Audacity.jss recipe is functionally identical to the jss-recipes/Audacity.jss recipe, except for `POLICY_TRIGGER`. Is the policy trigger something you use? If so, maybe we could make it an overrideable part of the jss-recipes recipe.

**Comment by novaksam** [comment]
@homebysix Yeah, I use the `POLICY_TRIGGER` was part of my 'master' software update policy (they are executed by a script), so I can fire off a bunch of policies sequentially, rather than having to update activation dates for every one.

That's pretty much the only reason I maintain my own jss recipes, though I do contribute to the jss-recipes repo, on occasion.

**Comment by timsutton** [comment]
@novaksam Yeah, I just meant that if there's unneeded duplication it's always better for anyone doing a search for recipes to have fewer choices. If there's a significant difference in the recipe that makes it not possible to consolidate them, then it's recommended to put that info into the Description so it's clear where they differentiate.
