### ISSUE TITLE
AdobeReader Fails

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/novaksam-recipes#84]
smatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
Receipt written to /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/receipts/Adobe Acrobat Reader DC.jss-receipt-20220129-004835.plist

The following recipes failed:
    Adobe Acrobat Reader DC.jss.recipe
        Error in com.github.novaksam.jss.AdobeAcrobatReaderDC: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

The following new items were downloaded:
    Download Path                                                                                                                       
    -------------                                                                                                                       
    /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/downloads/Adobe Acrobat Reader DC-21.011.20039.dmg 
Processing Adobe Acrobat Reader DC.jss.recipe...
WARNING: Adobe Acrobat Reader DC.jss.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
AdobeReaderURLProvider
AdobeReaderURLProvider: Found URL http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/2101120039/AcroRdrDC_2101120039_MUI.dmg
AdobeReaderURLProvider: Found version 21.011.20039
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/downloads/Adobe Acrobat Reader DC-21.011.20039.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/downloads/Adobe Acrobat Reader DC-21.011.20039.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.DFkuHq/AcroRdrDC_2101120039_MUI.pkg' matched from globbed '/private/tmp/dmg.DFkuHq/*.pkg'.
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "AcroRdrDC_2101120039_MUI.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-12-24 12:03:34 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Inc. (JQ525L2MZD)
CodeSignatureVerifier:        Expires: 2025-03-20 15:53:03 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            EB A4 77 C5 66 4C 70 60 7B CD 99 73 19 24 5D FF 1A 94 85 A9 32 37 
CodeSignatureVerifier:            CE 14 9C FD 5C B9 1A 39 CA C5
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/downloads/Adobe Acrobat Reader DC-21.011.20039.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.hKrrgY/AcroRdrDC_2101120039_MUI.pkg' matched from globbed '/private/tmp/dmg.hKrrgY/*.pkg'.
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "AcroRdrDC_2101120039_MUI.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-12-24 12:03:34 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Inc. (JQ525L2MZD)
CodeSignatureVerifier:        Expires: 2025-03-20 15:53:03 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            EB A4 77 C5 66 4C 70 60 7B CD 99 73 19 24 5D FF 1A 94 85 A9 32 37 
CodeSignatureVerifier:            CE 14 9C FD 5C B9 1A 39 CA C5
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: Adobe Systems, Inc. (JQ525L2MZD) -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: Adobe Inc. (JQ525L2MZD) -> Developer ID Certification Authority -> Apple Root CA
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
Receipt written to /Users/jobeng/Library/AutoPkg/Cache/com.github.novaksam.jss.AdobeAcrobatReaderDC/receipts/Adobe Acrobat Reader DC.jss-receipt-20220129-004857.plist

The following recipes failed:
    Adobe Acrobat Reader DC.jss.recipe
        Error in com.github.novaksam.jss.AdobeAcrobatReaderDC: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

above are the errors. Please kindly look into it and resolve

**Comment by novaksam** [comment]
@tsinghzf  Please try again, I updated the string in the PKG recipe.

**Comment by MLBZ521** [comment]
This was fixed in 3f82b08421ec3d97ef174440f96feef52626864a.
