### ISSUE TITLE
Xcode JSS recipe gives an error related to Info.plist

### ISSUE THREAD

**Issue by krispayne** [autopkg/novaksam-recipes#9]
![screen shot 2017-03-01 at 12 43 22 pm](https://cloud.githubusercontent.com/assets/70580/23480953/9e744402-fe7e-11e6-9102-590363d12f51.png)

When I run this recipe I get the above error. Is there additional setup I need to do to make this one work? I think this is the only recipe that I have that is using the appstore processor.

FWIW I am signed in to the App Store

**Comment by novaksam** [comment]
That's really weird, every App should have an info.plist file under contents...

Could you send a screenshot of the 'Get Info' for your XCode.app? And is it right under the /Applications/ folder? Or in a different subfolder?

**Comment by krispayne** [comment]
I don't currently have Xcode installed on my autopkg machine. Should I? Was just going to use it to put in my jss

**Comment by novaksam** [comment]
@krispayne 

The appstore processors require that the application be installed on the box running the recipes; there isn't, to my knowledge, an automatic way to pull down applications from the App Store (at least without VPP). I personally have a dedicated box that I use for running recipes that have all of my App Store apps installed on it, just so I can run AutoPkg.

Does that make sense?

**Comment by krispayne** [comment]
Yeah that makes sense. I figured there might be some reason related to the appstore processor. This is my first appstore app I'm trying to autopkg. Let me install Xcode and see what happens then.

**Comment by krispayne** [comment]
After installing XCode, the recipe is definitely moving forward more than it did previously. I think we can safely close this.
