### ISSUE TITLE
Adoptium JDK issues

### ISSUE THREAD

**Issue by kevinmcox** [autopkg/novaksam-recipes#93]
It looks like something went wrong with this commit:
https://github.com/autopkg/novaksam-recipes/commit/606bea1c8728c61a1c896fb7dde763bd6dc26d84

Two of the recipes are using the same Android Studio identifier and download information. While the third is pointing to the Adoptium Github releases but still checking for Google code signature on the package.

**Comment by kevinmcox** [comment]
I PR'ed #94 to temporarily address this.

**Comment by novaksam** [comment]
Have you looked at com.github.beatlemike.pkg.EclipseTemurin17 ?

**Comment by novaksam** [comment]
Ohhhh.,.. wait I think those are sitting in a PR on his repo...

**Comment by kevinmcox** [comment]
Thanks Sam. I'm not actually trying to download the JDK, just needed to fix the duplicate identifiers so the Android Studio recipe would stop failing.
